/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline-variant": "#ccc4ce",
        "on-secondary-fixed-variant": "#891933",
        "secondary-container": "#fe7488",
        "surface-tint": "#6b557f",
        "on-error-container": "#93000a",
        "surface-container-low": "#fdeffe",
        "outline": "#7b757e",
        "surface-container-high": "#f1e4f2",
        "error": "#ba1a1a",
        "surface-dim": "#e3d6e4",
        "tertiary": "#4e2d21",
        "surface-container": "#f7eaf8",
        "error-container": "#ffdad6",
        "on-secondary-container": "#730425",
        "surface-container-highest": "#ebdeed",
        "inverse-surface": "#352e38",
        "primary-fixed": "#f0dbff",
        "primary-fixed-dim": "#d7bcec",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#efbbaa",
        "on-surface-variant": "#4a454d",
        "primary-container": "#58436b",
        "inverse-primary": "#d7bcec",
        "tertiary-fixed": "#ffdbcf",
        "on-primary-container": "#cdb2e1",
        "background": "#fff7fc",
        "on-tertiary-container": "#e4b1a1",
        "inverse-on-surface": "#faedfb",
        "surface": "#fff7fc",
        "on-surface": "#201923",
        "primary": "#402c53",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#fff7fc",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffb2b9",
        "on-background": "#201923",
        "on-secondary-fixed": "#400010",
        "surface-variant": "#ebdeed",
        "secondary": "#a93349",
        "secondary-fixed": "#ffdadc",
        "on-tertiary-fixed-variant": "#623e31",
        "on-primary-fixed-variant": "#533e66",
        "on-primary-fixed": "#251237",
        "on-secondary": "#ffffff",
        "tertiary-container": "#684336",
        "on-tertiary-fixed": "#2f140a"
      },
      fontFamily: {
        sans: ['"Be Vietnam Pro"', 'sans-serif'],
        heading: ['"Plus Jakarta Sans"', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
